x = 5

try:
  print(x)
except:
  print("An exception occurred")

print(x)